import 'package:flutter/material.dart';
import 'package:dart_pptx/dart_pptx.dart';
import 'package:universal_html/html.dart' as html;

void main() {
  runApp(const InkFormulationApp());
}

class InkFormulationApp extends StatelessWidget {
  const InkFormulationApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Ink Formulation Slide',
      theme: ThemeData(
        useMaterial3: true,
        colorScheme: ColorScheme.fromSeed(
          seedColor: const Color(0xFF1E3A8A),
          brightness: Brightness.light,
        ),
      ),
      home: const SlideScreen(),
      debugShowCheckedModeBanner: false,
    );
  }
}

class SlideScreen extends StatefulWidget {
  const SlideScreen({super.key});

  @override
  State<SlideScreen> createState() => _SlideScreenState();
}

class _SlideScreenState extends State<SlideScreen> {
  // Constants and variables
  final double tvPercentage = 40.0;
  double basePercentage = 30.0;

  double get varnishPercentage => 100.0 - tvPercentage - basePercentage;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: Colors.grey[200],
      body: Center(
        child: AspectRatio(
          aspectRatio: 16 / 9,
          child: Container(
            margin: const EdgeInsets.all(32.0),
            padding: const EdgeInsets.all(40.0),
            decoration: BoxDecoration(
              color: Colors.white,
              borderRadius: BorderRadius.circular(16.0),
              boxShadow: [
                BoxShadow(
                  color: Colors.black.withOpacity(0.1),
                  blurRadius: 20,
                  offset: const Offset(0, 10),
                ),
              ],
            ),
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                _buildHeader(),
                const SizedBox(height: 48),
                Expanded(
                  child: Row(
                    crossAxisAlignment: CrossAxisAlignment.start,
                    children: [
                      Expanded(
                        flex: 3,
                        child: _buildChartSection(),
                      ),
                      const SizedBox(width: 48),
                      Expanded(
                        flex: 2,
                        child: _buildControlsSection(),
                      ),
                    ],
                  ),
                ),
              ],
            ),
          ),
        ),
      ),
    );
  }

  Widget _buildHeader() {
    return Row(
      mainAxisAlignment: MainAxisAlignment.spaceBetween,
      children: [
        Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            Text(
              'Finished Ink Formulation',
              style: TextStyle(
                fontSize: 36,
                fontWeight: FontWeight.w800,
                color: Colors.blueGrey[900],
                letterSpacing: -0.5,
              ),
            ),
            const SizedBox(height: 8),
            Text(
              'Interactive composition guide for standard ink mixing',
              style: TextStyle(
                fontSize: 18,
                color: Colors.blueGrey[400],
              ),
            ),
          ],
        ),
        Row(
          children: [
            ElevatedButton.icon(
              onPressed: _exportToPptx,
              icon: const Icon(Icons.download),
              label: const Text('Export PPTX'),
              style: ElevatedButton.styleFrom(
                padding: const EdgeInsets.symmetric(horizontal: 20, vertical: 12),
              ),
            ),
            const SizedBox(width: 16),
            Container(
              padding: const EdgeInsets.symmetric(horizontal: 16, vertical: 8),
              decoration: BoxDecoration(
                color: Theme.of(context).colorScheme.primary.withOpacity(0.1),
                borderRadius: BorderRadius.circular(20),
              ),
              child: Text(
                '100% Total',
                style: TextStyle(
                  fontSize: 16,
                  fontWeight: FontWeight.bold,
                  color: Theme.of(context).colorScheme.primary,
                ),
              ),
            ),
          ],
        ),
      ],
    );
  }

  Future<void> _exportToPptx() async {
    final pres = Powerpoint();
    
    pres.addTitleSlide(
      title: 'Finished Ink Formulation'.toTextValue(),
      author: 'Generated by Could Code'.toTextValue(),
    );
    
    // Using addTitleSlide again because we don't know the exact signature of addTitleAndContentSlide from the basic fetch,
    // actually let's try addSlidesFromMarkdown!
    final markdown = '''
# Ink Formulation Details
- TV (Constant): ${tvPercentage.toStringAsFixed(0)}%
- Base: ${basePercentage.toStringAsFixed(0)}%
- Clear NC Varnish: ${varnishPercentage.toStringAsFixed(0)}%
''';
    
    try {
      await pres.addSlidesFromMarkdown(markdown);
      
      final bytes = await pres.save();
      if (bytes != null) {
        final blob = html.Blob([bytes], 'application/vnd.openxmlformats-officedocument.presentationml.presentation');
        final url = html.Url.createObjectUrlFromBlob(blob);
        final anchor = html.AnchorElement(href: url)
          ..setAttribute('download', 'ink_formulation.pptx')
          ..click();
        html.Url.revokeObjectUrl(url);
        
        if (mounted) {
          ScaffoldMessenger.of(context).showSnackBar(
            const SnackBar(content: Text('PPTX Downloaded Successfully!')),
          );
        }
      }
    } catch (e) {
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(content: Text('Failed to generate PPTX: \$e')),
        );
      }
    }
  }

  Widget _buildChartSection() {
    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      mainAxisAlignment: MainAxisAlignment.center,
      children: [
        const Text(
          'Composition Breakdown',
          style: TextStyle(
            fontSize: 22,
            fontWeight: FontWeight.w600,
          ),
        ),
        const SizedBox(height: 32),
        _buildStackedBar(),
        const SizedBox(height: 48),
        _buildLegend(),
      ],
    );
  }

  Widget _buildStackedBar() {
    return Container(
      height: 80,
      decoration: BoxDecoration(
        borderRadius: BorderRadius.circular(12),
        boxShadow: [
          BoxShadow(
            color: Colors.black.withOpacity(0.05),
            blurRadius: 10,
            offset: const Offset(0, 4),
          ),
        ],
      ),
      clipBehavior: Clip.antiAlias,
      child: Row(
        children: [
          _buildBarSegment(
            percentage: tvPercentage,
            color: const Color(0xFF1E3A8A), // Deep Blue
            label: 'TV',
          ),
          _buildBarSegment(
            percentage: basePercentage,
            color: const Color(0xFF047857), // Emerald Green
            label: 'Base',
          ),
          _buildBarSegment(
            percentage: varnishPercentage,
            color: const Color(0xFFD97706), // Amber
            label: 'Varnish',
          ),
        ],
      ),
    );
  }

  Widget _buildBarSegment({
    required double percentage,
    required Color color,
    required String label,
  }) {
    if (percentage <= 0) return const SizedBox.shrink();
    
    return Expanded(
      flex: (percentage * 10).toInt(),
      child: Container(
        color: color,
        child: Center(
          child: percentage > 5 // Only show text if segment is wide enough
              ? Text(
                  '${percentage.toStringAsFixed(0)}%',
                  style: const TextStyle(
                    color: Colors.white,
                    fontWeight: FontWeight.bold,
                    fontSize: 18,
                  ),
                )
              : null,
        ),
      ),
    );
  }

  Widget _buildLegend() {
    return Column(
      children: [
        _buildLegendItem(
          color: const Color(0xFF1E3A8A),
          title: 'TV (Constant)',
          percentage: tvPercentage,
          description: 'Fixed at 40%',
        ),
        const SizedBox(height: 16),
        _buildLegendItem(
          color: const Color(0xFF047857),
          title: 'Base',
          percentage: basePercentage,
          description: 'Variable between 10% and 60%',
        ),
        const SizedBox(height: 16),
        _buildLegendItem(
          color: const Color(0xFFD97706),
          title: 'Clear NC Varnish',
          percentage: varnishPercentage,
          description: 'Automatically adjusts (0% to 50%)',
        ),
      ],
    );
  }

  Widget _buildLegendItem({
    required Color color,
    required String title,
    required double percentage,
    required String description,
  }) {
    return Row(
      children: [
        Container(
          width: 24,
          height: 24,
          decoration: BoxDecoration(
            color: color,
            borderRadius: BorderRadius.circular(6),
          ),
        ),
        const SizedBox(width: 16),
        Expanded(
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              Text(
                title,
                style: const TextStyle(
                  fontSize: 18,
                  fontWeight: FontWeight.w600,
                ),
              ),
              Text(
                description,
                style: TextStyle(
                  fontSize: 14,
                  color: Colors.blueGrey[400],
                ),
              ),
            ],
          ),
        ),
        Text(
          '${percentage.toStringAsFixed(0)}%',
          style: TextStyle(
            fontSize: 24,
            fontWeight: FontWeight.bold,
            color: color,
          ),
        ),
      ],
    );
  }

  Widget _buildControlsSection() {
    return Container(
      padding: const EdgeInsets.all(32),
      decoration: BoxDecoration(
        color: Colors.grey[50],
        borderRadius: BorderRadius.circular(16),
        border: Border.all(color: Colors.grey[200]!),
      ),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        mainAxisAlignment: MainAxisAlignment.center,
        children: [
          const Text(
            'Adjust Formulation',
            style: TextStyle(
              fontSize: 22,
              fontWeight: FontWeight.w600,
            ),
          ),
          const SizedBox(height: 8),
          Text(
            'Move the slider to modify the Base percentage. Varnish will compensate to maintain 100% total.',
            style: TextStyle(
              fontSize: 14,
              color: Colors.blueGrey[400],
            ),
          ),
          const SizedBox(height: 48),
          Row(
            mainAxisAlignment: MainAxisAlignment.spaceBetween,
            children: [
              const Text(
                'Base %',
                style: TextStyle(
                  fontSize: 18,
                  fontWeight: FontWeight.w500,
                ),
              ),
              Text(
                '${basePercentage.toStringAsFixed(0)}%',
                style: const TextStyle(
                  fontSize: 20,
                  fontWeight: FontWeight.bold,
                  color: Color(0xFF047857),
                ),
              ),
            ],
          ),
          const SizedBox(height: 16),
          SliderTheme(
            data: SliderThemeData(
              activeTrackColor: const Color(0xFF047857),
              inactiveTrackColor: const Color(0xFF047857).withOpacity(0.2),
              thumbColor: const Color(0xFF047857),
              overlayColor: const Color(0xFF047857).withOpacity(0.1),
              trackHeight: 8,
            ),
            child: Slider(
              value: basePercentage,
              min: 10,
              max: 60,
              divisions: 50,
              label: '${basePercentage.toStringAsFixed(0)}%',
              onChanged: (value) {
                setState(() {
                  basePercentage = value;
                });
              },
            ),
          ),
          const SizedBox(height: 8),
          Row(
            mainAxisAlignment: MainAxisAlignment.spaceBetween,
            children: [
              Text('10%', style: TextStyle(color: Colors.grey[500])),
              Text('60%', style: TextStyle(color: Colors.grey[500])),
            ],
          ),
          const Spacer(),
          Container(
            padding: const EdgeInsets.all(16),
            decoration: BoxDecoration(
              color: Colors.blue[50],
              borderRadius: BorderRadius.circular(12),
              border: Border.all(color: Colors.blue[100]!),
            ),
            child: Row(
              children: [
                Icon(Icons.info_outline, color: Colors.blue[700]),
                const SizedBox(width: 12),
                Expanded(
                  child: Text(
                    'Example: $tvPercentage% TV, ${basePercentage.toStringAsFixed(0)}% base, ${varnishPercentage.toStringAsFixed(0)}% clear NC varnish = 100% finished ink',
                    style: TextStyle(
                      color: Colors.blue[900],
                      fontWeight: FontWeight.w500,
                    ),
                  ),
                ),
              ],
            ),
          ),
        ],
      ),
    );
  }
}
